#Server config
server.port=5000

#Files
legalprocesses.files.path=

#Database
spring.datasource.url=
spring.datasource.username=
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jdbc.show-sql=false

#Flyway
flyway.baselineOnMigrate=true

#Gemini Api Key
gemini.api.key=