-- Create table legal_process_file

DO $$
BEGIN
    IF EXISTS (SELECT FROM pg_tables WHERE schemaname = 'public' AND tablename = 'legal_process_file') THEN
        RAISE NOTICE 'The legal_process_file table already exists !';
    ELSE
        CREATE TABLE legal_process_file (
            id bigint PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
            file_name varchar(255) NOT NULL,
            file_path varchar(255) NOT NULL,
            file_size numeric(13) NOT NULL
        ) INHERITS (audit_data);

        RAISE NOTICE 'legal_process_file table created successfully.';
    END IF;
END $$;
